# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    env_file: .env
    image: postgres
    restart: always
    volumes:
     - ./data/postgres:/var/lib/postgresql
    ports:
     - 5432:5432
  kmptnzbot:
    env_file: .env
    build: .
    ports:
     - 3000:3000
    volumes:
     - ./config.yml:/opt/kmptnzbot/config.yml
     - ./files:/opt/kmptnzbot/bin/files
    restart: always
